# Generated by Django 6.0.3 on 2026-04-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
