# Generated by Django 6.0.3 on 2026-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_school_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
