# Generated by Django 6.0.3 on 2026-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_customer_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mac', 'Mac'), ('iPad', 'iPad'), ('Apple Watch', 'Apple Watch'), ('Apple Care +', 'Apple Care +'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
